#!/bin/sh -

main() {
    if [ "$#" -gt 0 ]
    then make_dockerfile "$@"
    else default_list
    fi
}

default_list() {
    BASE=Docker.d/Dockerfile
    mkdir -p Docker.d
    make_dockerfile > "$BASE.minbase"
    for RELEASE in jessie potato
    do make_dockerfile "$RELEASE" > "$BASE.$RELEASE"
    done
}

make_dockerfile() {
    local RELEASE="$1"
    local MIRROR="$3"
    local ARCH

    [ "$RELEASE" = potato ] && ARCH=i386
    [ "$ARCH" = '' ] && ARCH=amd64

    case "$RELEASE" in
    potato) MIRROR=http://archive.debian.org/debian ;;
    esac

    echo '# We can use any Linux that has debootstrap as a package.'
    echo '# Ideally we want the smallest that has up to date'
    echo '# repository keys for our final target'
    echo '#'

    cat <<\@
# Alpine is very small, but only has a Debian keyring.
FROM alpine AS unpack
RUN apk add perl debootstrap

@

	cat <<\@
# Add some more keyrings.
# The download is secured by https and the ca-certificates package.
RUN apk add git
WORKDIR /root
RUN git clone \
	-b ubuntu/devel \
	https://git.launchpad.net/ubuntu/+source/ubuntu-keyring
RUN cp -a ubuntu-keyring/keyrings/*.gpg /usr/share/keyrings/.
RUN git clone \
	https://git.devuan.org/devuan/devuan-keyring.git
RUN cp -a devuan-keyring/keyrings/*.gpg /usr/share/keyrings/.

@

    echo ARG RELEASE=${RELEASE:-stable}
    echo ARG ARCH=$ARCH
    echo ARG MIRROR=$MIRROR
    echo ARG DEBSCRIPT
    echo ARG DEBOPTIONS
    echo

    echo WORKDIR /opt
    echo '# Chroot under Docker is unreliable; use --foreign as a workaround.'

    echo 'RUN set -x;DIR=/usr/share/debootstrap/scripts;\'

    echo '    if grep -q ^keyring.*ubuntu "$DIR/${DEBSCRIPT:-$RELEASE}";then \'
    echo '    COMP="--components=main,restricted,universe,multiverse";else \'
    echo '    COMP="--components=main,contrib,non-free";fi;\'

    echo '    if grep -q ^variants.*minbase "$DIR/${DEBSCRIPT:-$RELEASE}";then \'
    echo '    VARIANT="--variant=minbase";fi;\'

    echo '    debootstrap --foreign --arch=$ARCH $VARIANT $COMP $DEBOPTIONS \'

    [ "$RELEASE" = jessie ] &&
	echo '    --exclude=systemd,systemd-sysv --include=sysvinit-core \'

    echo '    "$RELEASE" chroot $MIRROR $DEBSCRIPT'
    echo
    echo 'WORKDIR /opt/chroot'
    echo

    [ "$RELEASE" = potato ] && {
	echo '# It tries to mount proc, nope!'
	echo 'RUN sed -i -e '\''s/  setup_proc/#setup_proc/'\'' debootstrap/suite-script'
	echo
	echo '# Current debootstrap has bug'
	echo 'RUN sed -i -e '\''s/echo \${USE_COMPONENTS}/echo "\{USE_COMPONENTS}"/'\'' debootstrap/functions'
	echo
    }

    [ "$RELEASE" = jessie ] && {
	echo '# Systemd is unpacked ready to install even if we don'\''t want it.'
	echo '# So break the chroot such that it doesn'\''t actually get installed.'
	echo 'RUN sed -i -e '\''/systemd\>.*/d'\'' debootstrap/required'
	echo
    }

    echo '# Configure apt and dpkg for docker'
    echo '# Note: standard used "#" for comment not "//"'
    base64_extras
    echo

    echo '#------------------------------------------------------------------------------#'

    echo 'FROM scratch AS stage2'
    echo 'COPY --from=unpack /opt/chroot /'
    echo 'ARG DEBIAN_FRONTEND=noninteractive'
    echo 'ARG RELEASE'
    echo 'ARG ARCH'
    echo

    echo '# init sometimes uses ischroot to disable restarting.'
    echo 'RUN \'
    echo '    if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \'
    echo '    dpkg-divert --local --rename --add /usr/bin/ischroot;\'
    echo '    ln -s /bin/true /usr/bin/ischroot; fi'
    echo

    echo 'RUN set -x;: $RELEASE $ARCH; /debootstrap/debootstrap --second-stage'
    echo

    if [ "$RELEASE" = jessie ]
    then
	echo '# Systemd leaves a mess, unpack it again so dpkg can remove it.'
	echo 'RUN dpkg --unpack --force-depends /var/cache/apt/archives/systemd_*.deb'
	echo '# Sigh this breaks sysvinit ...'
	echo 'RUN dpkg --unpack --force-depends /var/cache/apt/archives/systemd-sysv_*.deb'
	echo '# Remove them'
	echo 'RUN dpkg --purge --force-depends systemd ||:'
	echo 'RUN dpkg --purge --force-depends systemd-sysv ||:'
	echo '# Oh, and fix sysvinit'
	echo 'RUN dpkg -i /var/cache/apt/archives/sysvinit-core_*.deb'
	echo ''
	echo '# Remove packages that are not essential'
	echo 'RUN apt-mark auto -qq $(apt-mark showmanual) \'
	echo '&&  apt-get autoremove --purge -y'
	echo
    else
	echo '# Clear all the manual install flags'
	echo 'RUN [ ! -f /usr/bin/apt-mark ] || apt-mark auto -qq $(apt-mark showmanual) ||:'
	echo
    fi

    echo '# Make sure everything is installed properly'
    echo 'RUN set -x;: $RELEASE $ARCH; dpkg --configure --pending'
    echo

    echo '# Clean up the divert I put in to stop sysvinit trying to restart itself'
    echo 'RUN \'
    echo '    if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \'
    echo '    rm -f /usr/bin/ischroot; \'
    echo '    dpkg-divert --local --rename --remove /usr/bin/ischroot;fi'
    echo

    echo '# Clean lists, cache and history.'
    echo 'RUN apt-get update -qq --list-cleanup -oDir::Etc::SourceList=/dev/null'
    echo 'RUN apt-get clean'
    echo 'RUN dpkg --clear-avail'
    echo 'RUN rm -f /etc/apt/apt.conf.d/01autoremove-kernels'
    echo 'RUN rm -f /var/lib/dpkg/*-old'
    echo 'RUN :|find /var/log -type f ! -name bootstrap.log -exec tee {} \;'
    echo 'RUN [ ! -x /usr/bin/dselect ] || dselect update'
    echo

    echo '#------------------------------------------------------------------------------#'
    echo '# Finally squash all the layers.'
    echo 'FROM scratch'
    echo 'COPY --from=stage2 / /'
    echo 'WORKDIR /root'
    echo 'CMD ["bash"]'
}

base64_extras() {

    tar c \
	--owner=root --group=root \
	--mode=og=u-w,ug-s \
	--mtime=/etc/os-release \
	-f - -- etc usr |
    {
	echo 'RUN set -eu; _() { echo "$@";};(\'
	gzip -n9 | base64 -w 72 | sed 's/.*/_ &;\\/'
	echo ')|base64 -d|gzip -d|tar xvf -'
    }
}

main "$@"
