#!/bin/sh
set -e

cd "$(dirname "$0")"

./update-builds.sh i386 current
./update-builds.sh current

for i in $(docker images reg.xz/*:* --format='{{.Repository}}:{{.Tag}}' |
    grep -v '<')
do docker push "$i"
done

for i in \
    buster bullseye bookworm testing sid unstable stable latest
do
    docker push rdebath/debian:$i reg.xz/debian:$i
    docker push rdebath/debian-i386:$i reg.xz/debian-i386:$i
done

docker push rdebath/debian:sid-x32 reg.xz/debian-x32:sid

# for i in focal groovy
# do docker push rdebath/ubuntu-i386:$i reg.xz/ubuntu-i386:$i
# done
# for i in ceres chimaera
# do docker push rdebath/devuan:$i-i386 reg.xz/devuan-i386:$i
# done
