# We need an older linux because potato's bash is so old.
FROM debian:stretch AS unpack
RUN apt-get update ; apt-get install -y -qq debootstrap

ARG RELEASE=potato
ARG ARCH=i386
ARG MIRROR=http://archive.debian.org/debian

WORKDIR /opt
# Chroot under Docker is unreliable; use --foreign as a workaround.
RUN debootstrap --arch=$ARCH --foreign "$RELEASE" chroot $MIRROR

WORKDIR /opt/chroot

# It tries to mount proc, nope!
RUN sed -i -e 's/  setup_proc/#setup_proc/' debootstrap/suite-script

# Configure apt and dpkg for docker (copied from official Debian; fixed comments)
RUN set -eu; e() { echo "$@";};\
(\
e H4sIAAAAAAACA+1abY8btxG+z/oV0zUQO4HedSe5chDAiZHigDYwbAf5UiCgdqkVe7vkhuRK;\
e lpv+9z5Dru50F5+LFD2dg3Jg+7xL7nDI4TzzDHnS56OzB5YxZHFxEX5C7v4M/5/M5ouL8/HF;\
e eDo9G0/Gs9nsjC7OTiCt88ISnVlj/Kf6/af2P6hI+F80fvR5+R+ySP4/pf/xd5gbvR4Wo0f1;\
e /2TM/p9hIyT/P5L/C5NfSTvIKyn0/8z/8/Pz+/w/nZ7PbuJ/PoH/L2ZTxP84+f/BZTSit0rn;\
e ktbGUm2cp1fB/dQ6aV2fGpFfiVKS0linqnK0EU0jNZ4pixuFVq2qioycl43r96DQb+SepHNS;\
e e4Vv9rSSualZR6G2qmhFRZXYQz0VrSRv+APaif1h6I3QRSUdqwr9lC770NfIPKprHd7Qd+Yn;\
e Wiv022Pk2g2JftoID13KUY2t68KUWkd49mjpLKNc5BsZX9HL1+/oSsJukrqgtqF/YDvAFOd5;\
e BIfJs9Xoa5zsbO5TLa7QyupMaw8zabWWOeYsrIKFlbBYs2dHNruwyDv5tKpIG1uHl1pu40p3;\
e trlr60QpMC7WgXYKX/DqS1FE8+6s+01XGCZJ0MrigTVquSNVw3tfDnv8fFlIHrbfDbUzbdWp;\
e XPE0t4bnRRmgYFBKTwEAsj7G8bwIPFkvw8p0XsYCYtlkWLiV5G/zfV6pPNotqTQeu6LNr8ho;\
e XuqnjiqY3idnQrPsvLVuNSvMrRReGR00o+/xDooTv23ZsPfq9VW5XL7Grh1csvmS/kmZrWmw;\
e ptFW2FFYzAhvNt+orXSjr4aFXN3b2gjLA36811fDFZbh11/J21ZmL+hfL3qY1HL5Y1MILx/V;\
e jt4rZZfL77jLctlclaEzZdmLWw3O5rfaeNF/MF5GV8IjhSH4oFIfZHSMcvqpD0GjeOuEGEW4;\
e FiY094OfhcWeq9AS4tUwNqDLSnqPLerasuQtYxCNzzbeN245GpXKb9oVsk09wuxaaa00ft/I;\
e O0/KuVY6bN2zJI+R/7UZVEKXLfDDPWj+H59Pj/j/Au8n8zlepfx/mvx/qbvE248YwDFv1h6B;\
e rCXAncM/e4ec4qoAzy6LabeD8aeI/+OsGVKDQrZncIgZdLWH1p2ujCg4SUBhHbEjgozeqJXy;\
e MSMji39vOvIRYakwMZVFS/Ch4twgkFDrppLIeQFoGJVkJX0HXGxgGOE6ZbQBpLMhLb/s9V7m;\
e v7TKAhH/etjglGmjAaa9FP+H+BetN1bWZisHHYy7h4n/yWwxP4p/1InT8WyS4v+0/P+Y9oek;\
e XpnIB5lFMwY45qzYBdQY59QKAbZWGqQgMEwXSCVH6tpUldnxh7KWlkNLcLiC6O4JKb8Gv2tC;\
e zOplICBEb378gW6HKf09trB88cV1Y1eD0GBPX3d1ifvmTt+vQU4cFxsYq1ERscB07dU39yht;\
e WqbqUDkIO34Qt/zRAMHKbwFhci3ayvdD0RBYuch9G9jpz1xD/HyoldzBUEDWVgl6w9VPDabs;\
e yFhW9ko24UmtgVEG62avy6y3XaR1WIf6IFJ7uKhqA3riI/ZG98E1ETdWlewOWJMLODGiZaRi;\
e R/YAG+MECyDtW5C0CMhcIgWczdaicjIDr3etPa6S0AOFnzWNVXAQRhFliQ4OdJXEyqBECHo7;\
e fGdVN6vhSRQoE2IRcmCBWH/l20IOwTexBkx0ldBDY0sGoJHUo3wznrrxBf4MN76unjA8qfIl;\
e /PYSjnoToemwYJd1Y6wX2vfQYbm86bFc/qbLYZYvErX8BP6XH1QzQMku3z80/1tc3D3/m88v;\
e Ev4/Iv7HE5bsI8j8cTgeDocZnrtjDGU7bYEndoyyPGJoSC6KQS62C3BNuxO2cIGA7jhCO/Bi;\
e hcAvZJCQffg/19nH6EGh3PVpgnzfVCpXHtBk5S8tJ6oIXo0PRzxBZThmQGJg5AIadiowkLk+;\
e YjFr2Hnoc6CrEbqYmXKLsMoZzRT2N/wyHgchPfgNY2JAViQgQcBNpscBGbOIdcvdRsoP+4xW;\
e wsmYRplEUzb98/D5c/rbtxnWA8lBBnUdWQ48GyqrfdD0fDhdzLjr8IjV/gWRexkDl7J4SND7;\
e VPwXzVX5kBdA/8X9z3Sezv9Phv/B//zPMF+XD3AB9Lvufxbh/meySPe/j+b/QwEIaHMNCu+2;\
e eeDzn/Hsjv/n83G6/zmJPAlZ7Xdc/BStDdzg1iUEJyqVb3pPkOxlODRG+bDl2qAxO/SqkLRD;\
e HYNUyRUIr7lHAg4H+UcEAH32G7PjnA5d8SpHaS5Ad1JcUcmH43ylI0grcJZud9Kzus034ZXl;\
e bOsapTUbycnd9aHJrLbKtK7a800ICtpcDlrtxFoOlPn/LgJaZz/L3/9ZTBL+n8r/bqX0Z8b/;\
e ZtPz5P+T+r8xKJ/2A5sPi1P7f7ZYsP/ni/F0Ed5PZufjScr/J8n/fxqx992m17uXCmR3Kv4s;\
e 1J8dIXD3MAKoi8VryPXh1ykkKEEeDgQiR+Bj2cAK4m3TWqiKz05p09bGIl3zfbMb0jvQAGhD;\
e Qb6VOhyN8m9jcO9wRLnaYwjTNF2tfjPM2pqa+Ki5buIxp4m2gALI9yikJ+NJOgBMkiRJkiRJ;\
e kiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiTJH1f+DWq7tGMAUAAA;\
)|base64 -d|gzip -d|tar xvf -

#------------------------------------------------------------------------------#
FROM scratch AS stage2
COPY --from=unpack /opt/chroot /

RUN /debootstrap/debootstrap --second-stage ||:

RUN echo deb http://archive.debian.org/debian potato main \
    > /etc/apt/sources.list

ARG DEBIAN_FRONTEND=noninteractive

# Clean lists, cache and history.
RUN apt-get update -qq --list-cleanup -oDir::Etc::SourceList=/dev/null
RUN apt-get clean
RUN echo > /var/lib/dpkg/available ; rm -f /var/lib/dpkg/*-old
RUN rm -f /etc/apt/apt.conf.d/01autoremove-kernels
RUN rm -f /var/log/apt/*

#------------------------------------------------------------------------------#
# Finally squash all the layers.
FROM scratch
COPY --from=stage2 / /
WORKDIR /root
CMD ["bash"]

