#!/bin/sh

TAG=build-qe-latest
TAB=$(echo .|tr . '\011')
git update-ref refs/tags/"$TAG" "$(
{
    echo 'Quantum Espresso with Miniconda' |
    echo "100644 blob $(git hash-object -w --stdin)${TAB}README.md"

    bash build.sh latest |
    echo "100644 blob $(git hash-object -w --stdin)${TAB}Dockerfile"

} | {
echo "tree $(git mktree)
author Autopost <> $(date +%s) +0000
committer Autopost <> $(date +%s) +0000

👻
" ; } | git hash-object -t commit -w --stdin )"

git push -f origin "$TAG"

