#--------------------------------------------------------------------------#
# We can use any Linux that has debootstrap as a package.
# Ideally we want the smallest that has up to date
# repository keys for our final target
#
# Alpine is very small, but only has a Debian keyring.
# So use git to fetch some others over https if needed.
FROM alpine AS unpack
WORKDIR /root

RUN : Configure host ;set -eu; _() { echo "$@";};(\
_ H4sIAAAAAAACA41TwW6cMBA9w1eMVlVWSmRQpfaC0py2VXOoEpH01CYrY8+CFbDp2E66f1+D;\
_ IWElpJSTmXkz857nObHogOHfNE14/wRcSmBMGya4aBAkVsY464j30CO1UCsXkLvr8kvuLeW2;\
_ 4YT5ApVbQap3NoAKKLHnisAQCELuEFxoucNnzzVMuCxNLEq4hA+hZ26VhN9pklzFXxmhIQLh;\
_ YwhbWzw+4ZGUriE7L+bjgsoUslMt4yQa9Yxsimd1XxfbZcdPKog8cN+6faeIAtfGub7IB1FZ;\
_ bJIZqvMOqUa5DbpaDexgYSI3EuVWKLWaqdC8+PawmgvMOo7E15NIGG/x1hPe3E0XNpMFZeH7;\
_ /f3tXZr8GnRsIo+uQtrAA5ydRYU1YQ/sz6j0cUWn3Z5WDnXjQpgaaz4q8HpwyO7rt/04b//j;\
_ uixvytO65bZ/Vl47P+83XXYLd30wJHDfyc9zgxdO7rh5F9YYTsc4Jw5Ik2BFEK3R+LrOCvyY;\
_ G5aP7RwedYaFBnzWcq9F03OZaXT5hL6wxodx0+9slTQR4eo4nEbfDHY+eGnVetlIM/p8SXNJ;\
_ ZOGseJwN+2rU8NAmBqeZ/2UwvGaJ8cX+A23qI5jlAwAA;\
)|base64 -d|gzip -d>/tmp/install;sh /tmp/install;rm -f /tmp/install

WORKDIR /opt
ARG RELEASE=stable
ARG ARCH
ARG MIRROR
ARG DEBSCRIPT
ARG DEBOPTIONS

RUN : Stage 1 ;set -eu; _() { echo "$@";};(\
_ H4sIAAAAAAACA5VU72vbMBD9HP8Vh2saKHHM2Cgjw4OsDSywJcXJxmDdimJfYq2O5OpHuhDy;\
_ v+8UOW3SsrL5iyTr3unp3T21NBqI8XfQ6kE4MWyB8ArmUkGUDT4N+pMBRP3s4mMYBK3LYZYm;\
_ VqtEl0xhUuBMSqONYnWic8Vro4PWdwj3wBBSqKVhRsIPOD0FlyYNo40bezF//fZ8Gz4D3EtZ;\
_ rP8jXjNFjP89vsCVZcIDNkEL6LscfJhcZMOrafoY+c5vNctUGzar0P/7PMyyceYO8rNeXBpT;\
_ 9xKnR9en70q1SJZIzApHYRu0jrmxZXH+Zusk5XNYKKwhvoOft7hWXCy6Z3ZmhbHEmwRPos0D;\
_ v1685+eymhIFXIw/X6VhHOdyWUuBwuh0ybjoKKS68Nxg0bGCr1Bp7CxtZfyU0Fhp/Cs6l4LQ;\
_ s46QIp4rdPFzTmwfqK6Y4ozCu2dLLmaMUr1IlsT22n3tZ8P+aOrObFKkTQInxpNS/UKtua+t;\
_ Rw++TbN+2o6pW/PKFpjqtTa4LDrNGNO4gjjm4mF7xQU3dD+FbTrgoGMpjJoc+ULQjKm8THdt;\
_ DlFDESInDkR0n/HVdDgeTeDas4h2NA6p5qWitBD5fthhvAZ0ZF5AImuT+JjAuexS5reooGQa;\
_ WKWQUb+TB20NSa1kHrQ0FhBz8iS0dQJ+78ZtJScH8zYc+c9yg7F3YfCiC5umP4ELqxSV/DDN;\
_ jtPMLnzIEQ/MSwnX0ebLZHDjlBmPBqPpZOv/h883wicE51bkhkuhnR1eKvWeoHuNfFmBa7Ci;\
_ ZqRaAV4vugwXZMqqAlyRDchG9wiFFG0D99RVwE03fMwjYUa4WyDL7IulbV7SmrlQAqJ2UJYb;\
_ SznXsKA3sTkAi32mAz2SpuOu33fPkuL4pgrvLFdY7Hzfg/2T6jxWocGjtzX4AxTWrEd+BQAA;\
)|base64 -d|gzip -d>/tmp/install;sh /tmp/install;rm -f /tmp/install

# Configure apt and dpkg for docker
# Note: standard used "#" for comment not "//"
WORKDIR /opt/chroot
RUN set -eu; _() { echo "$@";};(\
_ H4sIAAAAAAACA+1abY8btxG+z/oV0zUQO4G00kn34sqGASdGigPSwLAd5EuBgNqlVqx2yQ3J;\
_ lSw3+e99hlyddeeXokFP56Ac2He3Inc45HCeeYaU9MX45I5lArk8Pw+/Ibd/h79PZxfns9n0;\
_ dHJ2djI5ncxmkxM6PzmCdM4LS3RijfGf6/ef2v+kIuF/0frxl+V/yFny/zH9j/95YfQyL8df;\
_ gP9nk7OL5P978n9pirW0o6KWQv/P/H/Bfv24/6fTs9kt/5/jrxOaJP/fuYzH9FrpQtLSWGqM;\
_ 8/QiuJ86J60bUiuKtagkKY11qmtHK9G2UuOZsrhRaNGpuszIedm64QAK/UruSDontVd4Z0cL;\
_ WZiGdZRqo8pO1FSLHdRT2Unyhl+grdjth14JXdbSsarQT+lqCH2tLKK6zuET+s78TEuFfjuM;\
_ 3Lic6OeV8NClHDXYui5MqXOEZ4+W3jIqRLGS8SN6/vINrSXsJqlL6lr6J7YDTHGeR3CYPFuN;\
_ vsbJ3uYhNWKNVlZnOrufSae1LDBnYRUsrIXFmj06sNmFRd7Kh3VN2tgmfKjlJq50b5u7tk5U;\
_ AuNiHWir8AavvhRlNO/Wur/vCsMkCVpYPLBGLbekGnjv63zAz1el5GGH/VBb09W9ygVPc2N4;\
_ XpQBCkaV9BQAIBtiHM+LwJP1MqxM72UsIJZNhoVbSH632BW1KqLdkirjsSu6Yk1G81I/dFTD;\
_ 9CE5E5pl761lp1lhYaXwyuigGX0Pd1Cc+E3L8sGLl+tqPn+JXTu6YvMl/Ysy29BoSeONsOOw;\
_ mBHebLFSG+nG3+SlXHyytRWWB/x4r2/yBZbht9/I205mT+j3JwNMaj7/qS2Fl/dqx+CFsvP5;\
_ d9xlPm/XVehMWfbkRoOzxY02XvQfjZfRlfBIaQg+qNU7GR2jnH7oQ9Ao3johRhGupQnNw+Bn;\
_ YbHnarSEeDWMDeiykN5ji7quqnjLGETjo5X3rZuPx5Xyq26BbNOMMbtOWiuN37Xy1pNyrpMO;\
_ W/ckyX3kf21GtdBVB/xwd5r/J2fT2/zv4uJ0mvL/kfL/le4T7zBiAMe8WXoEspYAdw7/7A1y;\
_ iqsDPLsspt0exh8i/g+zZkgNCtmewSFm0MUOWre6NqLkJAGFTcSOCDJ6pRbKx4yMLP696clH;\
_ hKXSxFQWLcGLinODQEJt2loi5wWgYVSStfQ9cLGBYYTrlNEFkM5ymn89GDwvfu2UBSL+sN/g;\
_ lGmjAaaDFP/7+BedN1Y2ZiNHPYy7u4n/09nlxc34n06ml+cp/o/K/w9pf0jqtYl8kFk0Y4Bj;\
_ zopdQK1xTi0QYEulQQoCw3SBVHKkLk1dmy2/KBtpObQEhyuI7o6Q8hvwuzbErJ4HAkL06qcf;\
_ 6WaY0j9iC8tXX1039jUIjXb0tK9L3LNbfZ+CnDguNjBWqyJigena9bNPKG07pupQOQo7fhS3;\
_ /MEAwcpvAWFyKbraD0PREFi5KHwX2OkvXEP8sq+V3N5QQNZGCXrF1U8DpuzIWFb2QrbhSS2B;\
_ UQbrZq/LrNd9pPVYh/ogUnu4qO4CeuIl9kb/wjURN1ZV7A5YUwg4MaJlpGIH9gAb4wRLIO1r;\
_ kLQIyFwiBZzNlqJ2MgOvd509rJLQA4WfNa1VcBBGEVWFDg50lcTCoEQIent8Z1XvV8OTKFEm;\
_ xCJkzwKx/sp3pczBN7EGTHSV0LmxFQPQWOpxsZpM3eQc//KVb+oHDE+qeg6/PYejXkVo2i/Y;\
_ VdMa64X2A3SYz9/3mM8/6LKf5ZNELT+D/9U71Y5Qssu3d83/Ls8/5H98/pfw/77wP56wZB9B;\
_ 5o/DcZ7nGZ77Ywxle22BJ/aMsjpgaEguikEutgtwTbsVtnSBgG45QnvwYoXAL2SQkH34j+vs;\
_ Y/SoVO76NEG+bWtVKA9osvLXjhNVBK/WhyOeoDIcMyAxMHIBDXsVGMhcH7GYJezc99nT1Qhd;\
_ zEy5RVjljGYK+wG/jMdBSA9+xZgYkBUJSBBwk+lxQMYsYt18u5Ly3S6jhXAyplEm0ZRN/5o/;\
_ fkx//zbDeiA5yKCuJ8uBZ0NlvQuaHufTyxl3zQ9Y7d8QuVcxcCmLhwSDz8V/2a6ru7wA+gP3;\
_ P1N0T+f/R8L/4H/+kRfL6g4ugP7A/c/pxTT5/778vy8AAW2uReHdtXd8/nM6vZ3/zy9T/j+K;\
_ PAhZ7b+4+Ck7G7jBjUsITlSqWA0eINnLcGiM8mHDtUFrtuhVI2mHOgapkisQXnOPBBwO8g8I;\
_ APrsVmbLOR264lWO0lyAbqVYU8WH43ylI0grcJZ+d9KjpitW4SPL2da1Sms2kpO7G0KTWWyU;\
_ 6Vy945uQB0/NcvmM69pCjjrtxFKOlPk/rQU6Z7/I7/9cpPv/o/nfLZT+wvhfuP9P/j+i/1uD;\
_ 8mk3skVeHtv/s8vL2/zvbJK+/3Gc/P+XMXvfrZAXP0UFslsVfxbqz54QuE8wAqiLxWvI9eHr;\
_ FBKUoAgHApEj8LFsYAXxtmkpVM1np7TqGmORrvm+2eX0BjQA2lCQb6QOR6P8bQzuHY4oFzsM;\
_ Ydq2r9XfD7O0piE+am7aeMxpoi2gAPItCunTyWk6AEySJEmSJEmSJEmSJEmSJEmSJEmSJEmS;\
_ JEmSJEmSJEmSJEmSJEmSJMmfV/4NQR5c0wBQAAA=;\
)|base64 -d|gzip -d|tar xvf -
#--------------------------------------------------------------------------#

RUN : Stage 2 ;set -eu; _() { echo "$@";};(\
_ H4sIAAAAAAACA61V227bRhB9Fr9i7BhOa2S1jR/Z2oVbq0GAQAHsAH1InGC1OyS3IneZvagS;\
_ 4vx7Z5eUFNltekH5QJHcuZ05M0cTjwEYrosJrnvrAlzPfnp5Nf/wy83r+ZvZ/PrCWKNNQCdk;\
_ 0CssikkJ2ugA3nYYdIceoqeb9rJx1gYIFpT2YtEixF6JgH5aTHQFb4GtgfuFNjz7M5E/RO94;\
_ /rb1vysmoUEDql/WTFFKqomx1krR0q9DIzqkB6HUY+diAulqDTAP+SS4iH9mV+mM5E2jPdg+;\
_ aGtg4VAsfcZFCH0QbesB6xLiIpoQeSeoFi2XxSSVRiVU1klk0XhRIdMWWJuLhkuucMVNbFs4;\
_ vzx9DqenQ10eFTBNzYan/P2TH2xVXcKDGNzzJ2/fw90ZcP4U3o146OIYJE/R820qq3qquLJy;\
_ iY6JPjDfI6rYw/19ScCogAXB9MGJ/stnKtqjtEYxglcjWQ8ZUDYWjn+9upm/nL8oYbZO/AYR;\
_ oofK2Q6+EoL6d/LjMVyenhcjzccnN7NXs6vb2TFcwG/ovcYtqUO2Em43PmCnoEXqqQcBNEb+;\
_ GUTTC7kESi5qoQ1RMTRUCgMOO7uidGE6BBk5GF22ZCjs0SjifiUcl0I2yKk7XDjZ0CR57ofE;\
_ H86mBGlXja4bCGkStiOw8as8o9Pp/5GNpXiHKW8GNNST7iBBH12Nj+KPcTK5/9g6Z927lPC6;\
_ eQbCKKj0eofwy3D6aziyNZPW4QjkAZLUFxoHT5AE0ecQDO0ysYomaNrclJjipu1JfmlkO+GW;\
_ ICLpBfv4EU6+2X3zjf29EyaK9tu9dU0ylYzHOdiB3xyaDJLz6DMpUmCxr51Qw2He/7GNNM2V;\
_ rqPLUamF2tTbs3GjKQwshEdW6RY9eZKYVXtZ2VV+R7t+uAFH+xVIZ5/+HfyBvs9Zqn6mZTGE;\
_ Lw3NXm0HgfxPCjuU4roDKIdK+jcaPHLx1/I61NxS82m782DlQaBVIyI3VPVD2qgTlCeRJZMr;\
_ oWX2WruynAVZlrc20qC/ouOLncTuY2SPPan0RtK4EppMRpBJQ/Ng92GaSCcJ/e75fqgYianB;\
_ 1u/s0zq0ejHo7hmzrRqO3HgWup6TUucfgntfaQI3eFmqIWx6hAqO0t8rSgiI8OkzvPs+jc/R;\
_ ATXKY4uSmCHCYfsy9CS18TYr7TlI2/UtUp9o4WE7Y8Uf5BuWicIHAAA=;\
)|base64 -d|gzip -d>tmp/stage2

#--------------------------------------------------------------------------#
FROM scratch AS stage2
COPY --from=unpack /opt/chroot /
ARG RELEASE
RUN set -ex;: $RELEASE; sh /tmp/stage2 && rm -f /tmp/stage2
#--------------------------------------------------------------------------#
# Finally squash all the layers.
FROM scratch
COPY --from=stage2 / /
WORKDIR /root
CMD ["bash"]
