# We can use any Linux that has debootstrap as a package.
FROM alpine AS unpack
RUN apk add perl debootstrap

ARG RELEASE=woody
ARG ARCH=i386
ARG MIRROR=http://archive.debian.org/debian

WORKDIR /opt
# Chroot under Docker is unreliable; use --foreign as a workaround.
RUN debootstrap --foreign \
    --arch=$ARCH  \
    "$RELEASE" chroot $MIRROR

WORKDIR /opt/chroot

# Configure apt and dpkg for docker
# Note: standard used "#" for comment not "//"
RUN set -eu; _() { echo "$@";};(\
_ H4sIAAAAAAACA+1abY/bNhLez/4VcwrQpIUte+19yTlFgbRBDwu0RZCk6JcDClqiZZ4lUiUp;\
_ O861/73PkPLGu3k5XNH1pigHye7KpIZDDueZZ0hLX4xP7lgmkMvz8/Abcvt3+Pt0dnE+m01P;\
_ J2dnJ5PTyWw2OaHzkyNI57ywRCfWGP+xfv+r/S8qEv4XrR9/Wv6HnCX/H9P/+J8XRi/zcvwJ;\
_ +H82ObtI/r8n/5emWEs7Kmop9J/m/wv26/v9P52ezW75/xx/ndAk+f/OZTyml0oXkpbGUmOc;\
_ p2fB/dQ5ad2QWlGsRSVJaaxTXTtaibaVGs+UxY1Ci07VZUbOy9YNB1DoV3JH0jmpvcI7O1rI;\
_ wjSso1QbVXaiplrsoJ7KTpI3/AJtxW4/9ErospaOVYV+SldD6GtlEdV1Dp/QN+YnWir022Hk;\
_ xuVEP62Ehy7lqMHWdWFKnSM8e7T0llEhipWMH9HT569oLWE3SV1S19J/sB1givM8gsPk2Wr0;\
_ NU72Ng+pEWu0sjrT2f1MOq1lgTkLq2BhLSzW7NGBzS4s8lY+rGvSxjbhQy03caV729y1daIS;\
_ GBfrQFuFN3j1pSijebfW/W1XGCZJ0MLigTVquSXVwHuf5wN+violDzvsh9qaru5VLniaG8Pz;\
_ ogxQMKqkpwAA2RDjeF4EnqyXYWV6L2MBsWwyLNxC8rvFrqhVEe2WVBmPXdEVazKal/qhoxqm;\
_ D8mZ0Cx7by07zQoLK4VXRgfN6Hu4g+LEb1qWD549X1fz+XPs2tEVmy/pv5TZhkZLGm+EHYfF;\
_ jPBmi5XaSDf+Ii/l4oOtrbA84Pt7fZEvsAy//kredjJ7Qr89GWBS8/mPbSm8vFc7Bs+Unc+/;\
_ 4S7zebuuQmfKsic3GpwtbrTxov9gvIyuhEdKQ/BBrd7I6Bjl9EMfgkbx1gkxinAtTWgeBj8L;\
_ iz1XoyXEq2FsQJeF9B5b1HVVxVvGIBofrbxv3Xw8rpRfdQtkm2aM2XXSWmn8rpW3npRznXTY;\
_ uidJ7iP/azOqha464Ie70/w/OZve5n8XF6fTlP+PlP+vdJ94hxEDOObN0iOQtQS4c/hnr5BT;\
_ XB3g2WUx7fYw/hDxf5g1Q2pQyPYMDjGDLnbQutW1ESUnCShsInZEkNErtVA+ZmRk8W9NTz4i;\
_ LJUmprJoCV5UnBsEEmrT1hI5LwANo5Kspe+Biw0MI1ynjC6AdJbT/PPB4GnxS6csEPG7/Qan;\
_ TBsNMB2k+N/Hv+i8sbIxGznqYdzdTfyfzi4vbsb/dDK9PE/xf1T+f0j7Q1KvTeSDzKIZAxxz;\
_ VuwCao1zaoEAWyoNUhAYpgukkiN1aerabPlF2UjLoSU4XEF0d4SU34DftSFm9TwQEKIXP/5A;\
_ N8OU/h1bWD777Lqxr0FotKMv+7rEfXWr75cgJ46LDYzVqohYYLp2/dUHlLYdU3WoHIUdP4pb;\
_ /mCAYOXXgDC5FF3th6FoCKxcFL4L7PRnriF+3tdKbm8oIGujBL3g6qcBU3ZkLCt7JtvwpJbA;\
_ KIN1s9dl1ss+0nqsQ30QqT1cVHcBPfESe6N/4ZqIG6sqdgesKQScGNEyUrEDe4CNcYIlkPYl;\
_ SFoEZC6RAs5mS1E7mYHXu84eVknogcLPmtYqOAijiKpCBwe6SmJhUCIEvT2+s6q3q+FJlCgT;\
_ YhGyZ4FYf+W7Uubgm1gDJrpK6NzYigFoLPW4WE2mbnKOf/nKN/UDhidVPYXfnsJRLyI07Rfs;\
_ qmmN9UL7ATrM5297zOfvdNnP8kmilh/B/+qNakco2eXru+Z/l+fv8j8+/0v4f1/4H09Ysvcg;\
_ 8/vhOM/zDM/9MYayvbbAE3tGWR0wNCQXxSAX2wW4pt0KW7pAQLccoT14sULgFzJIyD78x3X2;\
_ MXpUKnd9miBft7UqlAc0WflLx4kqglfrwxFPUBmOGZAYGLmAhr0KDGSuj1jMEnbu++zpaoQu;\
_ ZqbcIqxyRjOFfYdfxuMgpAe/YkwMyIoEJAi4yfQ4IGMWsW6+XUn5ZpfRQjgZ0yiTaMqm/8wf;\
_ P6bvv86wHkgOMqjryXLg2VBZ74Kmx/n0csZd8wNW+y9E7lUMXMriIcHgY/FftuvqLi+A/sD9;\
_ zxTd0/n/kfA/+J9/5MWyuoMLoD9w/3N6MU3+vy//7wtAQJtrUXh37R2f/0xu3/9cnF+m/H8U;\
_ eRCy2v9x8VN2NnCDG5cQnKhUsRo8QLKX4dAY5cOGa4PWbNGrRtIOdQxSJVcgvOYeCTgc5B8Q;\
_ APTZrcyWczp0xascpbkA3UqxpooPx/lKR5BW4Cz97qRHTVeswkeWs61rldZsJCd3N4Qms9go;\
_ 07l6xzchKGgLOeq0E0s5UubvXQR0zn6S3/+5SPf/R/O/Wyj9ifG/cP+f/H9E/7cG5dNuZIu8;\
_ PLb/Z5eXt/nf2SR9/+M4+f8fY/a+Ww0GH6QC2a2KPwv1Z08I3AcYAdTF4jXk+vB1CglKUIQD;\
_ gcgR+Fg2sIJ427QUquazU1p1jbFI13zf7HJ6BRoAbSjIN1KHo1H+Ngb3DkeUix2GMG3b1+pv;\
_ h1la0xAfNTdtPOY00RZQAPkahfTp5DQdACZJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJ;\
_ kiRJkiRJkiRJkuSvK78DrrpgNwBQAAA=;\
)|base64 -d|gzip -d|tar xvf -

#------------------------------------------------------------------------------#
FROM scratch AS stage2
COPY --from=unpack /opt/chroot /
ARG DEBIAN_FRONTEND=noninteractive
ARG RELEASE
ARG ARCH

RUN set -x;: $RELEASE $ARCH; /debootstrap/debootstrap --second-stage

# Clean lists, cache and history.
RUN apt-get update -qq --list-cleanup -oDir::Etc::SourceList=/dev/null
RUN apt-get clean
RUN dpkg --clear-avail; dpkg --clear-avail
RUN rm -f /etc/apt/apt.conf.d/01autoremove-kernels
RUN rm -f /var/log/apt/*

# clear-avail breaks dpkg
RUN echo > /var/lib/dpkg/available ; rm -f /var/lib/dpkg/*-old

#------------------------------------------------------------------------------#
# Finally squash all the layers.
FROM scratch
COPY --from=stage2 / /
WORKDIR /root
CMD ["bash"]
